# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6wi3b0VWOLyBzgt9NjUiuZdEQpECFR7
"""

import logging

logging.basicConfig(level=logging.INFO, format='%(message)s')
log = logging.getLogger(__name__)

class FormulaCNF:
    """
    Representa una fórmula en Forma Normal Conjuntiva (CNF)
    """
    def __init__(self, formula_str):
        self.original_formula = formula_str
        self.clauses = self._parse_formula(formula_str)
        self.assignment = {}

    def _parse_formula(self, formula):
        """Parsea una fórmula en formato string a estructura de datos"""
        import re
        if formula == "":
            return []

        # Extraer cláusulas entre paréntesis
        clause_strings = re.findall(r'\([^)]+\)', formula)
        clauses = []

        for clause_str in clause_strings:

            literals_str = clause_str.strip('()').split('|')
            clause = []

            for lit in literals_str:
                lit = lit.strip()
                if lit.startswith('~'):
                    clause.append({'variable': lit[1:].strip(), 'negated': True})
                else:
                    clause.append({'variable': lit.strip(), 'negated': False})

            clauses.append(clause)

        return clauses

    def empty_sentence(self):
        """Verifica si la fórmula está vacía (no tiene cláusulas)"""
        return len(self.clauses) == 0

    def has_empty_clause(self):
        """Verifica si existe alguna cláusula vacía"""
        return any(len(clause) == 0 for clause in self.clauses)

    def find_unit_clause(self):
        """Encuentra un literal en una cláusula unitaria"""
        for clause in self.clauses:
            if len(clause) == 1:
                return clause[0]['variable']
        return None

    def find_pure_literal(self):
        """Encuentra un literal puro (aparece solo positivo o solo negado)"""
        literal_polarities = {}

        # Analizar todas las apariciones de cada literal
        for clause in self.clauses:
            for literal in clause:
                var = literal['variable']
                if var not in literal_polarities:
                    literal_polarities[var] = {'positive': False, 'negative': False}

                if literal['negated']:
                    literal_polarities[var]['negative'] = True
                else:
                    literal_polarities[var]['positive'] = True

        # Buscar literales que solo aparecen en una polaridad
        for var, polarities in literal_polarities.items():
            if polarities['positive'] and not polarities['negative']:
                return var
            if polarities['negative'] and not polarities['positive']:
                return var

        return None

    def choose_literal(self):
        """Elige un literal para ramificación"""
        if self.clauses and self.clauses[0]:
            return self.clauses[0][0]['variable']
        return None

    def assign(self, variable, value):
        """
        Crea una nueva fórmula con la asignación del literal
        y simplifica las cláusulas
        """
        new_formula = FormulaCNF("")
        new_formula.assignment = {**self.assignment, variable: value}
        new_formula.clauses = []

        for clause in self.clauses:
            clause_satisfied = False
            new_clause = []

            for literal in clause:
                if literal['variable'] == variable:
                    literal_value = not value if literal['negated'] else value
                    if literal_value:
                        clause_satisfied = True
                        break
                else:
                    new_clause.append(literal)

            if not clause_satisfied:
                new_formula.clauses.append(new_clause)

        return new_formula

    def __str__(self):
        """Representación en string de la fórmula"""
        if not self.clauses:
            return "[]"

        clause_strs = []
        for clause in self.clauses:
            literals = []
            for lit in clause:
                lit_str = ('~' if lit['negated'] else '') + lit['variable']
                literals.append(lit_str)
            clause_strs.append('(' + ' | '.join(literals) + ')')

        return ' & '.join(clause_strs)


class DPLL:
    """
    DPLL algorithm
    """

    @staticmethod
    def satisfiable(phi):
        """
        determines if phi is satisfiable
        :param phi: a CNF formula
        :returs: una tupla cuyo primer elemento indica
        si la fórmula es satisfactible o no, y el segundo
        la asignación que logró hacer la fórmula verdadera
        """
        log.info("phi: "+str(phi))
        if phi.empty_sentence():
            log.info("sentencia vacia")
            return (True, phi.assignment)

        if phi.has_empty_clause():
            log.info("clausula vacia encontrada")
            return (False, None)

        unit_literal = phi.find_unit_clause()
        if unit_literal is not None:
            log.info(f"literal unitario encontrado: {unit_literal}")
            new_phi = phi.assign(unit_literal, True)
            return DPLL.satisfiable(new_phi)

        pure_literal = phi.find_pure_literal()
        if pure_literal is not None:
            log.info(f"literal puro encontrado: {pure_literal}")
            value = True
            new_phi = phi.assign(pure_literal, value)
            return DPLL.satisfiable(new_phi)

        literal = phi.choose_literal()
        log.info(f"ramificando en literal: {literal}")

        new_phi_true = phi.assign(literal, True)
        result = DPLL.satisfiable(new_phi_true)
        if result[0]:
            return result

        new_phi_false = phi.assign(literal, False)
        return DPLL.satisfiable(new_phi_false)


# Ejecutar el ejemplo
if __name__ == "__main__":
    print("="*60)
    print("EJECUTANDO DPLL CON LA FÓRMULA PHI_1")
    print("="*60)

    phi_1 = FormulaCNF("(~x1 | x3 | x4) & (~x2 | x6 | x4) & (~x2 | ~x6 | ~x3) & (~x4 | ~x2) & (x2 | ~x3 | ~x1) & (x2 | x6 | x3) & (x2 | ~x6 | ~x4) & (x1 | x5) & (x1 | x6) & (~x6 | x3 | ~x5) & (x1 | ~x3 | ~x5)")

    resultado = DPLL.satisfiable(phi_1)

    print("\n" + "="*60)
    print("RESULTADO FINAL")
    print("="*60)
    print(f"Satisfactible: {resultado[0]}")
    if resultado[1] is not None:
        print(f"Asignación: {resultado[1]}")
    else:
        print("Asignación: None")
    print("="*60)

pip install numpy